baseURL = 'https://adityabhardwaj.dev/'
languageCode = 'en-us'
title = 'Aditya Bhardwaj'
theme = 'archie'
publishDir = "docs"

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Welcome to my blog | Writeups and Musings"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support