baseURL = 'https://adityabhardwaj.dev/'
languageCode = 'en-us'
title = 'Aditya Bhardwaj'
theme = 'archie'
publishDir = "docs"
copyright = "© Aditya"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Cybersecurity student in ELTE | [Amateur DJ](https://www.youtube.com/@Psyklopp)"
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support


[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/psyklopp"

[[params.social]]
name = "YouTube"
icon = "youtube"
url = "https://www.youtube.com/@Psyklopp"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/ab4dev"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4